version: "3.7"
services:
  java:
    restart: always
    container_name: DeployCrud
    image: java:8
    volumes:
    - .:/usr/src/myapp 
    working_dir: /usr/src/myapp
    command: bash -c "cd target && java -jar CrudApi-0.0.1-SNAPSHOT.jar"  
    
